// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQA8tbollWXxerrTzPLIfsYflpCgW4b88',
    appId: '1:180971609431:web:c276f1966368fb9340b212',
    messagingSenderId: '180971609431',
    projectId: 'flutter-sports-app-85a14',
    authDomain: 'flutter-sports-app-85a14.firebaseapp.com',
    storageBucket: 'flutter-sports-app-85a14.appspot.com',
    measurementId: 'G-FPLS5ZY55L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54BV40zqxkwJ2kLUe-YGvIPjYzuQwCKw',
    appId: '1:180971609431:android:9d575e10b870834840b212',
    messagingSenderId: '180971609431',
    projectId: 'flutter-sports-app-85a14',
    storageBucket: 'flutter-sports-app-85a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtgO_i4Rzsmx3UnCwpBc4HMEXyHsodfE4',
    appId: '1:180971609431:ios:6ca98505a2cf176f40b212',
    messagingSenderId: '180971609431',
    projectId: 'flutter-sports-app-85a14',
    storageBucket: 'flutter-sports-app-85a14.appspot.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtgO_i4Rzsmx3UnCwpBc4HMEXyHsodfE4',
    appId: '1:180971609431:ios:4e1c2164114fafcd40b212',
    messagingSenderId: '180971609431',
    projectId: 'flutter-sports-app-85a14',
    storageBucket: 'flutter-sports-app-85a14.appspot.com',
    iosBundleId: 'com.example.sportsApp.RunnerTests',
  );
}
